# Generated by Django 2.1.4 on 2019-02-24 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalRowTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total', to='app.Total')),
                ('total_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_row', to='app.Total')),
            ],
        ),
        migrations.RemoveField(
            model_name='counterhistory',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='totalhistory',
            name='totlal',
        ),
        migrations.DeleteModel(
            name='CounterHistory',
        ),
        migrations.DeleteModel(
            name='TotalHistory',
        ),
    ]
