# Generated by Django 2.1.3 on 2018-11-24 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Counter')),
            ],
        ),
        migrations.CreateModel(
            name='TotalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('totlal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Total')),
            ],
        ),
    ]
